apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-drone-db-config
  label:
    app: ci-drone-db
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: supersecurepassword
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ci-drone-db
spec:
  serviceName: ci-drone-db
  selector:
    matchLabels:
      app: ci-drone-db
  replicas: 1
  template:
    metadata:
      labels:
        app: ci-drone-db
    spec:
      containers:
        - name: ci-drone-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: ci-drone-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          gcePersistentDisk:
            pdName: ci-prod-drone-postgres-data
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: ci-drone-db
  labels:
    app: ci-drone-db
spec:
  selector:
    app: ci-drone-db
  ports:
    - protocol: TCP
      name: postgres
      port: 5432
      targetPort: 5432